[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = localdev2026tz
admin_passwd = localadmin2026tz
db_name = odoo
log_level = info
workers = 0
max_cron_threads = 1
list_db = False
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 600
limit_time_real = 1200
