{
    'name': 'Импорт заказов на закупку из PDF (ИИ)',
    'version': '18.0.1.0.0',
    'category': 'Purchases',
    'summary': 'Импорт строк заказа на закупку из PDF поставщика с помощью ИИ',
    'depends': ['purchase', 'purchase_stock', 'stock', 'account', 'mail', 'analytic'],
    'data': [
        'security/purchase_roles.xml',
        'security/ir.model.access.csv',
        'security/purchase_request_security.xml',
        'data/purchase_request_data.xml',
        'data/analytic_category_data.xml',
        'wizard/pdf_import_settings_views.xml',
        'wizard/pdf_import_wizard_views.xml',
        'wizard/payment_import_wizard_views.xml',
        'wizard/updd_import_wizard_views.xml',
        'wizard/request_split_wizard_views.xml',
        'wizard/request_merge_wizard_views.xml',
        'views/purchase_updd_line_views.xml',
        'views/purchase_request_views.xml',
        'views/purchase_menus.xml',
        'views/purchase_order_line_extra_views.xml',
        'views/purchase_order_priority_views.xml',
        'views/purchase_approval_views.xml',
        'views/purchase_registry_views.xml',
        'views/purchase_payment_views.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/res_users_roles_matrix_views.xml',
        'views/warehouse_scrap_request_views.xml',
        'views/warehouse_location_views.xml',
        'views/core_menu_visibility.xml',
        'views/stock_picking_purchase_link.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'purchase_pdf_import/static/src/scss/chatter_hide_send_message.scss',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
    'post_init_hook': 'seed_default_analytic_account',
}
